apiVersion: v1
kind: ConfigMap
metadata:
  name: config-ui-configmap
data:
  CONFIG_SERVICE_HOST: {{ .Values.app.configService.host }}
  CONFIG_SERVICE_PORT: "{{ .Values.app.configService.port }}"
  CONFIG_SERVICE_USER: {{ .Values.app.configService.user }}
  SERVICE_PORT: "{{ .Values.app.configUI.port }}"
  SERVICE_USERNAME: {{ .Values.app.configUI.user }}