apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-configmap
data:
  BINDING_ADDRESS: {{ .Values.app.dns.bindingAddress }}
  BINDING_PORT: "{{ .Values.app.dns.port }}"
  CONFIG_SERVICE_HOST: {{ .Values.app.configService.host }}
  CONFIG_SERVICE_PORT: "{{ .Values.app.configService.port }}"
  CONFIG_SERVICE_USERNAME: {{ .Values.app.configService.user }}