apiVersion: v1
kind: Service
metadata:
  annotations:
    appName: {{ include "common.fullname" . }}
    componentName: dns
  labels:
    io.kompose.service: dns
  name: dns
spec:
  ports:
    - name: tcp
      port: {{ .Values.service.ports.dns.port }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.dns.targetPort }}
    - name: udp
      port: {{ .Values.service.ports.dns.port }}
      protocol: UDP
      targetPort: {{ .Values.service.ports.dns.targetPort }}
  type: NodePort
  selector:
    io.kompose.service: dns
status:
  loadBalancer: {}
