apiVersion: v1
kind: ConfigMap
metadata:
  name: james-configmap
data:
  CONFIG_SERVICE_HOST: {{ .Values.app.configService.host }}
  CONFIG_SERVICE_PORT: "{{ .Values.app.configService.port }}"
  CONFIG_SERVICE_USERNAME: {{ .Values.app.configService.user }}
  IMAP_PORT: "{{ .Values.app.james.port2 }}"
  POP_PORT: "{{ .Values.app.james.port4 }}"
  RABBIT_MQ_HOST: {{ .Values.app.rabbitmq.host }}
  RABBIT_MQ_PORT: "{{ .Values.app.rabbitmq.port1 }}"
  RABBIT_MQ_USERNAME: {{ .Values.app.rabbitmq.user }}
  SERVICE_PORT: "{{ .Values.app.james.port1 }}"
  SMTP_PORT: "{{ .Values.app.james.port3 }}"
  WEBADMIN_PORT: "{{ .Values.app.james.port1 }}"
  WEBADMIN_USERNAME: {{ .Values.app.james.user }}