apiVersion: v1
kind: Service
metadata:
  annotations:
    appName: {{ include "common.fullname" . }}
    componentName: james-server
  labels:
    io.kompose.service: james-server
  name: james-server
spec:
  ports:
    - name: "{{ .Values.service.ports.james.port1 }}"
      port: {{ .Values.service.ports.james.port1 }}
      targetPort: {{ .Values.service.ports.james.targetPort1 }}
    - name: "{{ .Values.service.ports.james.port2 }}"
      port: {{ .Values.service.ports.james.port2 }}
      targetPort: {{ .Values.service.ports.james.targetPort2 }}
    - name: "{{ .Values.service.ports.james.port3 }}"
      port: {{ .Values.service.ports.james.port3 }}
      targetPort: {{ .Values.service.ports.james.targetPort3 }}
  type: LoadBalancer
  selector:
    io.kompose.service: james-server
status:
  loadBalancer: {}
