apiVersion: v1
kind: Service
metadata:
  annotations:
    appName: {{ include "common.fullname" . }}
    componentName: mysql
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
    - name: "{{ .Values.service.ports.mysql.port }}"
      port: {{ .Values.service.ports.mysql.port }}
      targetPort: {{ .Values.service.ports.mysql.targetPort }}
  type: LoadBalancer
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
