apiVersion: v1
items:
  - apiVersion: v1
    data:
      livenessCheck.sh: |
        #!/usr/bin/expect
        #exp_internal 1

        set timeout -1
        set smtp [lindex $argv 0]
        set port [lindex $argv 1]
        spawn telnet $smtp $port
        expect -re {[2]{2,}[0]{1,}}
        sleep 5;
        send -- "EHLO argv 0 \r"
        expect -re {[2]{1,}[5]{1,}[0]{1,}}
        send -- "quit\r"

        expect eof
    kind: ConfigMap
    metadata:
      name:  smtp-mq-gateway-liveness-configmap
kind: List
metadata: {}
