apiVersion: v1
kind: Service
metadata:
  annotations:
    appName: {{ include "common.fullname" . }}
    componentName: smtp-mq-gateway
  labels:
    io.kompose.service: smtp-mq-gateway
  name: smtp-mq-gateway
spec:
  ports:
    - name: "{{ .Values.service.ports.smtpMQgateway.port }}"
      port: {{ .Values.service.ports.smtpMQgateway.port }}
      targetPort: {{ .Values.service.ports.smtpMQgateway.targetPort }}
  type: LoadBalancer
  selector:
    io.kompose.service: smtp-mq-gateway
status:
  loadBalancer: {}
