apiVersion: v1
kind: Service
metadata:
  annotations:
    appName: {{ include "common.fullname" . }}
    componentName: sta
  labels:
    io.kompose.service: sta
  name: sta
spec:
  ports:
    - name: "{{ .Values.service.ports.sta.port }}"
      port: {{ .Values.service.ports.sta.port }}
      targetPort: {{ .Values.service.ports.sta.targetPort }}
  type: LoadBalancer
  selector:
    io.kompose.service: sta
status:
  loadBalancer: {}
